# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/ef06acb4-ede4-4357-a41c-910d5f6617bc";
      fsType = "btrfs";
      options = [ "compress=zstd:5" "noatime" "discard=async" "ssd" "space_cache=v2" "subvol=root" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/ef06acb4-ede4-4357-a41c-910d5f6617bc";
      fsType = "btrfs";
      options = [ "compress=zstd:5" "noatime" "discard=async" "ssd" "space_cache=v2" "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/ef06acb4-ede4-4357-a41c-910d5f6617bc";
      fsType = "btrfs";
      options = [ "compress=zstd:5" "noatime" "discard=async" "ssd" "space_cache=v2" "subvol=nix" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/ef06acb4-ede4-4357-a41c-910d5f6617bc";
      fsType = "btrfs";
      options = [ "compress=zstd:5" "noatime" "discard=async" "ssd" "space_cache=v2" "subvol=opt" ];
    };

  fileSystems."/efi" =
    { device = "/dev/disk/by-uuid/47A3-EBB9";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };
  
  fileSystems."/home/ja/00-Shared-Drives/Common-nvme" =
    { device = "/dev/disk/by-uuid/e127528d-777a-4c14-a492-da23db715427";
      fsType = "ext4";
    };
  
  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
